import type { Card, PlayTypeResult, PlayType } from './types';
export declare function createDeck(): Card[];
export declare function shuffle<T>(array: T[]): T[];
export declare function compareCards(a: Card, b: Card): number;
export declare function sortHand(hand: Card[]): Card[];
export declare function cardValue(card: Card): number;
export declare function cardsEqual(a: Card, b: Card): boolean;
export declare function isThreeOfDiamonds(card: Card): boolean;
export declare function findStarterIndex(hands: Card[][]): number;
export declare function getPlayType(cards: Card[]): PlayTypeResult | null;
export declare function canBeat(newCards: Card[], currentPlay: Card[] | null, currentPlayType: PlayTypeResult | null): boolean;
export declare function getPlayTypeName(type: PlayType): string;
export declare function includesThreeOfDiamonds(cards: Card[]): boolean;
export declare function dealCards(numPlayers: number): Card[][];
export declare function removeCardsFromHand(hand: Card[], cardsToRemove: Card[]): Card[];
export declare function hasUnusedTwos(hand: Card[]): boolean;
export declare function hasUnusedQuads(hand: Card[]): boolean;
export declare function hasUnusedStraightFlush(hand: Card[]): boolean;
export declare function calculatePoints(cardsRemaining: number, hasUnusedTwos: boolean, hasUnusedQuads: boolean, hasUnusedStraightFlush: boolean, winnerEndedWithSpecial: boolean): number;
